<div class="row">
    <div class="span12">
    	<h2>Lazy loading module on Zend Framework 2</h2>
        <h3>Introduction</h3>
            <p>For this project, i redefined a party of the module manager to 
            have a lazy loading and increase the performance.</p>
            <p>The cache key will be automatically update with the module loaded.</p>
        <h3>Code</h3>
            <p>Available on <a href="https://github.com/blanchonvincent/zf2-lazy-loading-module" target="_blank">Github</a> : <a href="https://github.com/blanchonvincent/zf2-lazy-loading-module" target="_blank">blanchonvincent/zf2-lazy-loading-module</a></p>
        <h3>Lazy Loading module usage</h3>
            <p>Lazy loading module concept can load only authorize module for the current environment.</p>
            <h3>Exemples in this app</h3>
            <p>Rules to load modules :</p>
            <ul>
                <li>Always load "Application" module</li>
                <li>"Administration" module load in server port 443</li>
                <li>"Blog" will be loaded in domain "blog.zend-framework-2.fr" and white list IP control</li>
                <li>"Auth" module loaded with a HTTP simple authentification</li>
                <li>Load "Cron" module only in CLI and with a "cron" argument to run app with url in argument</li>
            </ul>
            <p>To complete the rules, use this config :</p>
            <?php 
                $contents = file_get_contents(__DIR__.'/../../../../config/application.config.php');
                $contents = htmlentities($contents);
                $contents = preg_replace("#\\n#", "</li><li>", $contents);
                $contents = preg_replace("#\/\/#", "", $contents);
            ?>
            <pre style="margin-bottom: 18px;" class="prettyprint linenums"><ol class="linenums"><li><?php echo $contents; ?></li></ol></pre>
            <p>Navigate with the menu and look which modules are loaded.</p>
        <h3>Filter available</h3>
        <ul>
            <li>Argument in command line</li>
            <li>SAPI</li>
            <li>HTTPS protocol</li>
            <li>Server port</li>
            <li>URL control</li>
            <li>Domain control</li>
            <li>Remote address client</li>
        </ul>
    </div> 
</div>
