<?php
return array(
    'ZFBook\Mvc\Application'                    => __DIR__ . '/../vendor/ZFBook/Mvc/Application.php',
    'ZFBook\Module\Manager'                     => __DIR__ . '/../vendor/ZFBook/Module/Manager.php',
    'ZFBook\Module\ModuleEvent'                 => __DIR__ . '/../vendor/ZFBook/Module/ModuleEvent.php',
    'ZFBook\Module\Listener\Config\LazyLoading'    => __DIR__ . '/../vendor/ZFBook/Module/Listener/Config/LazyLoading.php',
    'ZFBook\Module\Listener\ConfigListener'    	=> __DIR__ . '/../vendor/ZFBook/Module/Listener/ConfigListener.php',
    'ZFBook\Module\Listener\ListenerOptions'    => __DIR__ . '/../vendor/ZFBook/Module/Listener/ListenerOptions.php',
    'ZFBook\Module\Listener\AuthorizeHandler'   => __DIR__ . '/../vendor/ZFBook/Module/Listener/AuthorizeHandler.php',
    'ZFBook\Module\Listener\EnvironmentHandler' => __DIR__ . '/../vendor/ZFBook/Module/Listener/EnvironmentHandler.php',
    'ZFBook\Module\Listener\AbstractListener'   => __DIR__ . '/../vendor/ZFBook/Module/Listener/AbstractListener.php',
    'ZFBook\Module\Listener\EnvironmentListenerAggregate'   => __DIR__ . '/../vendor/ZFBook/Module/Listener/EnvironmentListenerAggregate.php',
    'ZFBook\Module\Listener\Environment\GetoptListener'     => __DIR__ . '/../vendor/ZFBook/Module/Listener/Environment/GetoptListener.php',
    'ZFBook\Module\Listener\Environment\SapiListener'       => __DIR__ . '/../vendor/ZFBook/Module/Listener/Environment/SapiListener.php',
    'ZFBook\Module\Listener\Server\AbstractListener'   => __DIR__ . '/../vendor/ZFBook/Module/Listener/Server/AbstractListener.php',
    'ZFBook\Module\Listener\Server\HttpsListener'     => __DIR__ . '/../vendor/ZFBook/Module/Listener/Server/HttpsListener.php',
    'ZFBook\Module\Listener\Server\RemoteAddrListener'     => __DIR__ . '/../vendor/ZFBook/Module/Listener/Server/RemoteAddrListener.php',
    'ZFBook\Module\Listener\Server\PortListener'     => __DIR__ . '/../vendor/ZFBook/Module/Listener/Server/PortListener.php',
    'ZFBook\Module\Listener\Server\DomainListener'     => __DIR__ . '/../vendor/ZFBook/Module/Listener/Server/DomainListener.php',
    'ZFBook\Module\Listener\Server\UrlListener'     => __DIR__ . '/../vendor/ZFBook/Module/Listener/Server/UrlListener.php',
);
