<?php
return array(
    'ZFMLL\Mvc\RouteListener' => __DIR__ . '/../vendor/ZFMLL/Mvc/RouteListener.php',
    'ZFMLL\Mvc\Service\ModuleManagerFactory' => __DIR__ . '/../vendor/ZFMLL/Mvc/Service/ModuleManagerFactory.php',
    'ZFMLL\ModuleManager\ModuleManager' => __DIR__ . '/../vendor/ZFMLL/ModuleManager/ModuleManager.php',
    'ZFMLL\ModuleManager\ModuleEvent' => __DIR__ . '/../vendor/ZFMLL/ModuleManager/ModuleEvent.php',
    'ZFMLL\ModuleManager\Exception' => __DIR__ . '/../vendor/ZFMLL/ModuleManager/Exception.php',
    'ZFMLL\ModuleManager\Listener\Exception\InvalidListenerException' => __DIR__ . '/../vendor/ZFMLL/ModuleManager/Listener/Exception/InvalidListenerException.php',
    'ZFMLL\ModuleManager\Listener\Exception\InvalidArgumentException' => __DIR__ . '/../vendor/ZFMLL/ModuleManager/Listener/Exception/InvalidArgumentException.php',
    'ZFMLL\ModuleManager\Listener\Config\LazyLoading' => __DIR__ . '/../vendor/ZFMLL/ModuleManager/Listener/Config/LazyLoading.php',
    'ZFMLL\ModuleManager\Listener\ConfigListener' => __DIR__ . '/../vendor/ZFMLL/ModuleManager/Listener/ConfigListener.php',
    'ZFMLL\ModuleManager\Listener\ListenerManager' => __DIR__ . '/../vendor/ZFMLL/ModuleManager/Listener/ListenerManager.php',
    'ZFMLL\ModuleManager\Listener\ListenerBroker' => __DIR__ . '/../vendor/ZFMLL/ModuleManager/Listener/ListenerBroker.php',
    'ZFMLL\ModuleManager\Listener\ListenerLoader' => __DIR__ . '/../vendor/ZFMLL/ModuleManager/Listener/ListenerLoader.php',
    'ZFMLL\ModuleManager\Listener\ListenerOptions' => __DIR__ . '/../vendor/ZFMLL/ModuleManager/Listener/ListenerOptions.php',
    'ZFMLL\ModuleManager\Listener\AuthorizeHandler' => __DIR__ . '/../vendor/ZFMLL/ModuleManager/Listener/AuthorizeHandler.php',
    'ZFMLL\ModuleManager\Listener\EnvironmentHandler' => __DIR__ . '/../vendor/ZFMLL/ModuleManager/Listener/EnvironmentHandler.php',
    'ZFMLL\ModuleManager\Listener\AbstractListener' => __DIR__ . '/../vendor/ZFMLL/ModuleManager/Listener/AbstractListener.php',
    'ZFMLL\ModuleManager\Listener\EnvironmentListenerAggregate' => __DIR__ . '/../vendor/ZFMLL/ModuleManager/Listener/EnvironmentListenerAggregate.php',
    'ZFMLL\ModuleManager\Listener\Environment\GetoptListener' => __DIR__ . '/../vendor/ZFMLL/ModuleManager/Listener/Environment/GetoptListener.php',
    'ZFMLL\ModuleManager\Listener\Environment\SapiListener' => __DIR__ . '/../vendor/ZFMLL/ModuleManager/Listener/Environment/SapiListener.php',
    'ZFMLL\ModuleManager\Listener\Server\HttpsListener' => __DIR__ . '/../vendor/ZFMLL/ModuleManager/Listener/Server/HttpsListener.php',
    'ZFMLL\ModuleManager\Listener\Server\RemoteAddrListener' => __DIR__ . '/../vendor/ZFMLL/ModuleManager/Listener/Server/RemoteAddrListener.php',
    'ZFMLL\ModuleManager\Listener\Server\PortListener' => __DIR__ . '/../vendor/ZFMLL/ModuleManager/Listener/Server/PortListener.php',
    'ZFMLL\ModuleManager\Listener\Server\DomainListener' => __DIR__ . '/../vendor/ZFMLL/ModuleManager/Listener/Server/DomainListener.php',
    'ZFMLL\ModuleManager\Listener\Server\UrlListener' => __DIR__ . '/../vendor/ZFMLL/ModuleManager/Listener/Server/UrlListener.php',
);