<?php
return array(
    'ZFMLL\Mvc\Application'                    => __DIR__ . '/../vendor/ZFMLL/Mvc/Application.php',
    'ZFMLL\Module\Manager'                     => __DIR__ . '/../vendor/ZFMLL/Module/Manager.php',
    'ZFMLL\Module\ModuleEvent'                 => __DIR__ . '/../vendor/ZFMLL/Module/ModuleEvent.php',
    'ZFMLL\Module\Exception'    				=> __DIR__ . '/../vendor/ZFMLL/Module/Exception.php',
    'ZFMLL\Module\Listener\Exception\InvalidHelperException'    => __DIR__ . '/../vendor/ZFMLL/Module/Listener/Exception/InvalidHelperException.php',
	'ZFMLL\Module\Listener\Exception\InvalidArgumentException'    => __DIR__ . '/../vendor/ZFMLL/Module/Listener/Exception/InvalidArgumentException.php',
    'ZFMLL\Module\Listener\Config\LazyLoading'    => __DIR__ . '/../vendor/ZFMLL/Module/Listener/Config/LazyLoading.php',
    'ZFMLL\Module\Listener\ConfigListener'    	=> __DIR__ . '/../vendor/ZFMLL/Module/Listener/ConfigListener.php',
    'ZFMLL\Module\Listener\ListenerManager'    => __DIR__ . '/../vendor/ZFMLL/Module/Listener/ListenerManager.php',
	'ZFMLL\Module\Listener\ListenerBroker'    => __DIR__ . '/../vendor/ZFMLL/Module/Listener/ListenerBroker.php',
	'ZFMLL\Module\Listener\ListenerLoader'    => __DIR__ . '/../vendor/ZFMLL/Module/Listener/ListenerLoader.php',
    'ZFMLL\Module\Listener\ListenerOptions'    => __DIR__ . '/../vendor/ZFMLL/Module/Listener/ListenerOptions.php',
    'ZFMLL\Module\Listener\AuthorizeHandler'   => __DIR__ . '/../vendor/ZFMLL/Module/Listener/AuthorizeHandler.php',
    'ZFMLL\Module\Listener\EnvironmentHandler' => __DIR__ . '/../vendor/ZFMLL/Module/Listener/EnvironmentHandler.php',
    'ZFMLL\Module\Listener\AbstractListener'   => __DIR__ . '/../vendor/ZFMLL/Module/Listener/AbstractListener.php',
    'ZFMLL\Module\Listener\EnvironmentListenerAggregate'   => __DIR__ . '/../vendor/ZFMLL/Module/Listener/EnvironmentListenerAggregate.php',
    'ZFMLL\Module\Listener\Environment\GetoptListener'     => __DIR__ . '/../vendor/ZFMLL/Module/Listener/Environment/GetoptListener.php',
    'ZFMLL\Module\Listener\Environment\SapiListener'       => __DIR__ . '/../vendor/ZFMLL/Module/Listener/Environment/SapiListener.php',
    'ZFMLL\Module\Listener\Server\AbstractListener'   => __DIR__ . '/../vendor/ZFMLL/Module/Listener/Server/AbstractListener.php',
    'ZFMLL\Module\Listener\Server\HttpsListener'     => __DIR__ . '/../vendor/ZFMLL/Module/Listener/Server/HttpsListener.php',
    'ZFMLL\Module\Listener\Server\RemoteAddrListener'     => __DIR__ . '/../vendor/ZFMLL/Module/Listener/Server/RemoteAddrListener.php',
    'ZFMLL\Module\Listener\Server\PortListener'     => __DIR__ . '/../vendor/ZFMLL/Module/Listener/Server/PortListener.php',
    'ZFMLL\Module\Listener\Server\DomainListener'     => __DIR__ . '/../vendor/ZFMLL/Module/Listener/Server/DomainListener.php',
    'ZFMLL\Module\Listener\Server\UrlListener'     => __DIR__ . '/../vendor/ZFMLL/Module/Listener/Server/UrlListener.php',
);
