<?php 
$this->headTitle()->setSeparator(' - ')
                  ->setAutoEscape(false);

$basePath = $this->basePath();
$this->headLink()->appendStylesheet($basePath . '/css/bootstrap.min.css')
                 ->appendStylesheet($basePath . '/css/style.css')
                 ->appendStylesheet($basePath . '/css/bootstrap-responsive.min.css');

$this->headLink(array(
            'rel'  => 'shortcut icon',
            'type' => 'image/vnd.microsoft.icon',
            'href' => $basePath . '/images/favicon.ico',
        ));

// HTML5 shim, for IE6-8 support of HTML elements
$this->headScript()->appendFile($basePath . '/js/html5.js', 'text/javascript', 
    array('conditional' => 'lt IE9',));

echo $this->doctype();
?>

<html lang="en">
  <head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('ZF2 Lazy loading module') ?>

    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

    <!-- Le styles -->
    <?php echo $this->headLink() ?>
    
    <!-- Scripts -->
    <?php echo $this->headScript() ?>

  </head>

  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">

            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="<?php echo $this->url('home') ?>">ZF2 Lazy loading module<?php echo $this->url() ?></a>
          <div class="nav-collapse">
            <ul class="nav">
              <li class=""><a href="<?php echo $this->url('app') ?>">Application</a></li>
              <li class=""><a href="<?php echo $this->url('admin-load') ?>">Admin</a></li>
              <li class=""><a href="<?php echo $this->url('blog-home') ?>">Blog</a></li>
              <li class=""><a href="<?php echo $this->url('cron-load') ?>">Cron</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">

      <?php echo $this->content; ?>

      <hr>

      <footer>
        <p><a href="https://github.com/blanchonvincent/zf2-lazy-loading-module" target="_blank">Github Zend Framework 2 lazy loading module</a> - <a href="http://au-coeur-de-zend-framework-2.fr/" target="_blank">Livre "Au coeur de Zend Framework 2"</a> - <a href="http://developpeur-zend-framework.fr" target="_blank">Développeur Zend Framework 2</a></p>
      </footer>

    </div>

  </body>
</html>
